'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Download, FileText, Image, Printer, Loader2 } from 'lucide-react';
import { Reading } from '@/lib/types';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

interface ExportButtonProps {
  reading: Reading;
  variant?: 'default' | 'outline' | 'ghost';
  size?: 'default' | 'sm' | 'lg' | 'icon';
}

export function ExportButton({ reading, variant = 'outline', size = 'sm' }: ExportButtonProps) {
  const [exporting, setExporting] = useState(false);

  const spreadTypeLabels: Record<string, string> = {
    'one-card': '원 카드',
    'three-card': '쓰리 카드',
    'celtic-cross': '켈틱 크로스',
  };

  const categoryLabels: Record<string, string> = {
    'love': '연애',
    'career': '커리어',
    'health': '건강',
    'general': '일반',
  };

  // PDF 내보내기
  const handleExportPDF = async () => {
    try {
      setExporting(true);

      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = pdf.internal.pageSize.getWidth();
      const pageHeight = pdf.internal.pageSize.getHeight();
      const margin = 20;
      let yPosition = margin;

      // 제목
      pdf.setFontSize(20);
      pdf.text('Unwoldam Tarot', margin, yPosition);
      yPosition += 10;

      // 구분선
      pdf.setLineWidth(0.5);
      pdf.line(margin, yPosition, pageWidth - margin, yPosition);
      yPosition += 10;

      // 질문
      pdf.setFontSize(16);
      pdf.text('질문', margin, yPosition);
      yPosition += 7;

      pdf.setFontSize(12);
      const questionLines = pdf.splitTextToSize(reading.question, pageWidth - 2 * margin);
      pdf.text(questionLines, margin, yPosition);
      yPosition += questionLines.length * 7 + 5;

      // 리딩 정보
      pdf.setFontSize(10);
      pdf.setTextColor(100);
      pdf.text(
        `${spreadTypeLabels[reading.spreadType]} | ${categoryLabels[reading.category]} | ${new Date(reading.createdAt).toLocaleDateString('ko-KR')}`,
        margin,
        yPosition
      );
      yPosition += 10;
      pdf.setTextColor(0);

      // 뽑은 카드
      pdf.setFontSize(14);
      pdf.text('뽑은 카드', margin, yPosition);
      yPosition += 7;

      pdf.setFontSize(10);
      reading.cards.forEach((cardData, index) => {
        const cardText = `${index + 1}. ${cardData.card.name}${cardData.isReversed ? ' (역방향)' : ''}`;
        pdf.text(cardText, margin + 5, yPosition);
        yPosition += 6;
      });
      yPosition += 5;

      // AI 해석
      pdf.setFontSize(14);
      pdf.text('AI 해석', margin, yPosition);
      yPosition += 7;

      pdf.setFontSize(10);
      const interpretationLines = pdf.splitTextToSize(
        reading.interpretation,
        pageWidth - 2 * margin
      );

      // 페이지 넘김 처리
      interpretationLines.forEach((line: string) => {
        if (yPosition > pageHeight - margin) {
          pdf.addPage();
          yPosition = margin;
        }
        pdf.text(line, margin, yPosition);
        yPosition += 5;
      });

      // Footer
      const totalPages = pdf.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        pdf.setPage(i);
        pdf.setFontSize(8);
        pdf.setTextColor(150);
        pdf.text(
          'Generated by Unwoldam Tarot - https://unwoldamstudio.vercel.app',
          pageWidth / 2,
          pageHeight - 10,
          { align: 'center' }
        );
        pdf.text(`${i} / ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
      }

      // 파일명 생성
      const fileName = `타로리딩_${reading.question.substring(0, 20)}_${new Date().toISOString().split('T')[0]}.pdf`;
      pdf.save(fileName);
    } catch (error) {
      console.error('PDF export error:', error);
      alert('PDF 내보내기 중 오류가 발생했습니다.');
    } finally {
      setExporting(false);
    }
  };

  // PNG 이미지로 내보내기
  const handleExportImage = async () => {
    try {
      setExporting(true);

      // 리딩 상세 페이지의 메인 콘텐츠 캡처
      const element = document.querySelector('main') as HTMLElement;
      if (!element) {
        alert('콘텐츠를 찾을 수 없습니다.');
        return;
      }

      const canvas = await html2canvas(element, {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
      });

      // Canvas를 Blob으로 변환
      canvas.toBlob((blob) => {
        if (!blob) return;

        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `타로리딩_${reading.question.substring(0, 20)}_${new Date().toISOString().split('T')[0]}.png`;
        link.click();
        URL.revokeObjectURL(url);
      });
    } catch (error) {
      console.error('Image export error:', error);
      alert('이미지 내보내기 중 오류가 발생했습니다.');
    } finally {
      setExporting(false);
    }
  };

  // 인쇄
  const handlePrint = () => {
    window.print();
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant={variant} size={size} disabled={exporting}>
          {exporting ? (
            <>
              <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              내보내는 중...
            </>
          ) : (
            <>
              <Download className="h-4 w-4 mr-2" />
              내보내기
            </>
          )}
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={handleExportPDF}>
          <FileText className="h-4 w-4 mr-2" />
          PDF로 저장
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handleExportImage}>
          <Image className="h-4 w-4 mr-2" />
          이미지로 저장
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handlePrint}>
          <Printer className="h-4 w-4 mr-2" />
          인쇄
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
