#!/bin/bash

# 타로 카드 파일명 목록 생성 스크립트
# 이 파일을 참고하여 다운로드한 이미지 파일명을 변경하세요

echo "=== 타로 카드 78장 파일명 목록 ==="
echo ""

echo "### Major Arcana (메이저 아르카나) - 22장 ###"
echo "ar00.jpg  # The Fool"
echo "ar01.jpg  # The Magician"
echo "ar02.jpg  # The High Priestess"
echo "ar03.jpg  # The Empress"
echo "ar04.jpg  # The Emperor"
echo "ar05.jpg  # The Hierophant"
echo "ar06.jpg  # The Lovers"
echo "ar07.jpg  # The Chariot"
echo "ar08.jpg  # Strength"
echo "ar09.jpg  # The Hermit"
echo "ar10.jpg  # Wheel of Fortune"
echo "ar11.jpg  # Justice"
echo "ar12.jpg  # The Hanged Man"
echo "ar13.jpg  # Death"
echo "ar14.jpg  # Temperance"
echo "ar15.jpg  # The Devil"
echo "ar16.jpg  # The Tower"
echo "ar17.jpg  # The Star"
echo "ar18.jpg  # The Moon"
echo "ar19.jpg  # The Sun"
echo "ar20.jpg  # Judgement"
echo "ar21.jpg  # The World"
echo ""

echo "### Cups (컵) - 14장 ###"
echo "cuac.jpg  # Ace of Cups"
echo "cu02.jpg  # Two of Cups"
echo "cu03.jpg  # Three of Cups"
echo "cu04.jpg  # Four of Cups"
echo "cu05.jpg  # Five of Cups"
echo "cu06.jpg  # Six of Cups"
echo "cu07.jpg  # Seven of Cups"
echo "cu08.jpg  # Eight of Cups"
echo "cu09.jpg  # Nine of Cups"
echo "cu10.jpg  # Ten of Cups"
echo "cupa.jpg  # Page of Cups"
echo "cukn.jpg  # Knight of Cups"
echo "cuqu.jpg  # Queen of Cups"
echo "cuki.jpg  # King of Cups"
echo ""

echo "### Wands (완드) - 14장 ###"
echo "waac.jpg  # Ace of Wands"
echo "wa02.jpg  # Two of Wands"
echo "wa03.jpg  # Three of Wands"
echo "wa04.jpg  # Four of Wands"
echo "wa05.jpg  # Five of Wands"
echo "wa06.jpg  # Six of Wands"
echo "wa07.jpg  # Seven of Wands"
echo "wa08.jpg  # Eight of Wands"
echo "wa09.jpg  # Nine of Wands"
echo "wa10.jpg  # Ten of Wands"
echo "wapa.jpg  # Page of Wands"
echo "wakn.jpg  # Knight of Wands"
echo "waqu.jpg  # Queen of Wands"
echo "waki.jpg  # King of Wands"
echo ""

echo "### Swords (소드) - 14장 ###"
echo "swac.jpg  # Ace of Swords"
echo "sw02.jpg  # Two of Swords"
echo "sw03.jpg  # Three of Swords"
echo "sw04.jpg  # Four of Swords"
echo "sw05.jpg  # Five of Swords"
echo "sw06.jpg  # Six of Swords"
echo "sw07.jpg  # Seven of Swords"
echo "sw08.jpg  # Eight of Swords"
echo "sw09.jpg  # Nine of Swords"
echo "sw10.jpg  # Ten of Swords"
echo "swpa.jpg  # Page of Swords"
echo "swkn.jpg  # Knight of Swords"
echo "swqu.jpg  # Queen of Swords"
echo "swki.jpg  # King of Swords"
echo ""

echo "### Pentacles (펜타클) - 14장 ###"
echo "peac.jpg  # Ace of Pentacles"
echo "pe02.jpg  # Two of Pentacles"
echo "pe03.jpg  # Three of Pentacles"
echo "pe04.jpg  # Four of Pentacles"
echo "pe05.jpg  # Five of Pentacles"
echo "pe06.jpg  # Six of Pentacles"
echo "pe07.jpg  # Seven of Pentacles"
echo "pe08.jpg  # Eight of Pentacles"
echo "pe09.jpg  # Nine of Pentacles"
echo "pe10.jpg  # Ten of Pentacles"
echo "pepa.jpg  # Page of Pentacles"
echo "pekn.jpg  # Knight of Pentacles"
echo "pequ.jpg  # Queen of Pentacles"
echo "peki.jpg  # King of Pentacles"
echo ""

echo "=== 총 78장 ==="
